name: API Tests with Cypress and Allure Report

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Use a versão desejada do Node.js

    - name: Install dependencies
      run: npm install

    - name: Start Local Server
      run: npx serverest
      background: true  # Inicia o servidor em segundo plano
    
    - name: Wait for Server to Start
      run: sleep 10  # Aguarda 10 segundos para que o servidor seja iniciado corretamente

    - name: Run Cypress tests and generate Allure report
      run: |
        npm run cypress:run
        npm run allure:report
        npm run allure:serve

    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: ./allure-report
