# This is a basic workflow to help you get started with Actions

name: Cadastro API ServeRest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - sandro-augusto

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3.5.3

      # Runs a set of commands using the runners shell
      - name: Step 1 Check version Allure, Node and Java
        run: |
          node --version
          java -version
          
      # Runs a single command using the runners shell      
      - name: Step 2 Install Dependences
        run: yarn install
        
      # Runs a set of commands using the runners shell
      - name: Step 3 Execute projets
        run: yarn cypress run --env allure=true
   
      # Runs a set of commands using the runners shell
      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
            name: report
            path: .allure-results/index.html
