name: Run Serverest and Generate Allure Reports

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Start Serverest
      run: npx serverest start

    - name: Run tests and generate Allure reports
      run: |
        npx cypress run
        npx allure generate --clean
        npx allure open

    - name: Stop Serverest
      run: npx serverest stop
